### ISSUE TITLE
No such file or directory: 'ngram-count': 'ngram-count'

### ISSUE THREAD

**Issue by sueyeontwigfarm** [rsennrich/multidomain_smt#1]
As I set the paths for Moses and GIZA++ and execute main.py,
I get the error message as below, 

```Training LM
ngram-count -interpolate -kndiscount -order 4 -unk -lm demo/demo_results/train1.lm -text demo/train1.de
Traceback (most recent call last):
  File "/Users/sueyeon/PycharmProjects/multidomain_smt/main.py", line 133, in <module>
    LMs.append(cluster.SRILM_interface(lm_name, order=LM_ORDER, text=textfile))
  File "/Users/sueyeon/PycharmProjects/multidomain_smt/cluster.py", line 276, in __init__
    self.train(text)
  File "/Users/sueyeon/PycharmProjects/multidomain_smt/cluster.py", line 283, in train
    p = Popen(cmd)
  File "/Users/sueyeon/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/sueyeon/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ngram-count': 'ngram-count'
```

I have no idea where to find the ngram-count file in the project. Can you clue me in on this issue?

**Comment by rsennrich** [comment]
ngram-count comes from SRILM: http://www.speech.sri.com/projects/srilm/

However, you can also replace this command with lmplz, which is included in Moses:

`lmplz -o 4 < demo/train1.de > demo/demo_results/train1.lm`

which will give (almost) the same results and be more efficient.
